export const APP_NAME = 'CreatorOS';
export const API_VERSION = 'v1';

export const ERROR_CODES = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  BAD_REQUEST: 'BAD_REQUEST',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  INSUFFICIENT_CREDITS: 'INSUFFICIENT_CREDITS',
  OAUTH_ERROR: 'OAUTH_ERROR',
  AI_PROVIDER_ERROR: 'AI_PROVIDER_ERROR',
} as const;

export const DEFAULT_PAGE_SIZE = 20;
export const MAX_PAGE_SIZE = 100;
